### ISSUE TITLE
Sanity tests failing with "No module named 'jinja2'"

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/kubernetes#66]
##### SUMMARY

```
ERROR: Command "importer.py" returned exit status 1.
>>> Standard Error
Traceback (most recent call last):
  File "/root/ansible/ansible_collections/community/kubernetes/tests/output/.tmp/sanity/import/minimal-py36/bin/importer.py", line 447, in <module>
    main()
  File "/root/ansible/ansible_collections/community/kubernetes/tests/output/.tmp/sanity/import/minimal-py36/bin/importer.py", line 51, in main
    from ansible.utils.collection_loader import AnsibleCollectionLoader
  File "/root/ansible/lib/ansible/utils/collection_loader.py", line 15, in <module>
    from ansible import constants as C
  File "/root/ansible/lib/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
ModuleNotFoundError: No module named 'jinja2'
```

See failed run: https://github.com/ansible-collections/kubernetes/runs/541824333

##### ISSUE TYPE

- Bug Report

**Comment by geerlingguy** [comment]
Seems to maybe be a bug in devel?

I'm installing with:

```
pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check
```

**Comment by geerlingguy** [comment]
Upstream issue: https://github.com/ansible/ansible/issues/68530

**Comment by geerlingguy** [comment]
The upstream issue has been fixed, and test runs are working again. Closing out this issue.
